### ISSUE TITLE
Python error while uploading file to AppSweep

### ISSUE THREAD

**Issue by LPLabrys99** [Guardsquare/appsweep-action#7]
Hi there, I've tried using the Github Action to upload a .apk file to AppSweep. The action code fails with a python error (looks like it's an issue with improper string handling?)

```python
Traceback (most recent call last):
  File "/app/main.py", line 73, in <module>
    input_file_id = upload_file(inputFile)
  File "/app/main.py", line 38, in upload_file
    print(resp.text + ' ' + resp.status_code)
TypeError: can only concatenate str (not "int") to str
```

**Comment by foadjn** [comment]
Hi @LPLabrys99,

Could you please give AppSweep GitHub action another try and let us know whether this solves your problem?
